version: '3'

services:
  db_postgres:
    image: postgres:14.7-alpine3.17
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.23.4-alpine
    ports:
      - 8001:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
      - static:/static
    depends_on:
      - django_app  

volumes:
  .:
  postgres_data:
  static:      